---
- name: Install Nginx apt key
  apt_key:
    url: https://nginx.org/keys/nginx_signing.key
    state: present

- name: Ensure latest nginx repository
  apt_repository:
    repo: "deb [ arch=amd64,arm64 ] https://nginx.org/packages/mainline/ubuntu/ {{ server.version|default('bionic') }} nginx"
    state: present
    update_cache: yes

- name: Install Nginx packages
  apt:
    update_cache: yes
    pkg:
      - nginx
    state: present
    cache_valid_time: 86400

- name: Make site directories
  file:
    path: "{{ app.installDir }}"
    state: directory
    owner: "{{ app.user }}"
    group: "{{ app.user }}"
    mode: 0775
  when: not isVagrant|default(False)

- name: Install nginx config
  template:
    src: "nginx.conf"
    dest: "/etc/nginx/nginx.conf"
  notify:
    - Restart nginx

- name: Delete default nginx config
  file:
    path: "/etc/nginx/conf.d/default.conf"
    state: absent
  notify:
    - Restart nginx

- name: Install nginx web configs
  template:
    src: "www.conf"
    dest: "/etc/nginx/conf.d/{{ app.id }}.conf"
  tags:
    - nginx_config
  notify:
    - Restart nginx
