---
- name: Install packages
  apt:
    update_cache: yes
    pkg: "{{ server.packages }}"
    state: present
    cache_valid_time: 86400

- name: Add app user
  user:
    name: "{{ app.user }}"
    state: present
  tags:
    - users