---
- name: Add multi-PHP ppa
  apt_repository:
    repo: "ppa:ondrej/php"
    state: present
    update_cache: yes

- name: Install PHP {{ server.php.version }} packages
  apt:
    update_cache: yes
    pkg:
      - "php{{ server.php.version }}"
      - "php{{ server.php.version }}-common"
      - "php{{ server.php.version }}-mbstring"
      - "php{{ server.php.version }}-fpm"
      - "php{{ server.php.version }}-mcrypt"
      - "php{{ server.php.version }}-gd"
      - "php{{ server.php.version }}-mysql"
      - "php{{ server.php.version }}-cli"
      - "php{{ server.php.version }}-curl"
      - "php{{ server.php.version }}-soap"
      - "php{{ server.php.version }}-imagick"
      - "php{{ server.php.version }}-intl"
      - "php{{ server.php.version }}-xml"
      - "php{{ server.php.version }}-zip"
      - "php{{ server.php.version }}-redis"
      - "php{{ server.php.version }}-bcmath"
    state: present
    cache_valid_time: 86400

- name: Copy PHP config files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - src: "php.ini"
      dest: "/etc/php/{{ server.php.version }}/fpm/php.ini"
    - src: "php.ini"
      dest: "/etc/php/{{ server.php.version }}/cli/php.ini"
    - src: "www.conf"
      dest: "/etc/php/{{ server.php.version }}/fpm/pool.d/www.conf"
  notify:
    - Restart FPM

- name: Check for Composer
  stat:
    path: /usr/bin/composer
  register: composer_file
  tags:
      - install_composer

- name: Download Composer
  get_url:
    url: https://getcomposer.org/installer
    dest: /tmp/composer-installer.php
    mode: 0755
  when: composer_file.stat.exists == False
  tags:
    - install_composer

- name: Install Composer
  command: |
    /usr/bin/php -d memory_limit=512M /tmp/composer-installer.php --install-dir=/usr/bin --filename=composer
  when: composer_file.stat.exists == False
  tags:
    - install_composer