---
- name: Install Percona apt key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 9334A25F8507EFA5
    state: present

- name: Add Percona apt server
  apt_repository:
    repo: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - "deb http://repo.percona.com/apt {{ server.version|default('bionic') }} main"
    - "deb-src http://repo.percona.com/apt {{ server.version|default('bionic') }} main"

- name: "Install supporting packages ({{ server.db.version|default('5.7') }})"
  apt:
    update_cache: yes
    pkg:
      - "percona-server-client-{{ server.db.version|default('5.7') }}"
      - "percona-server-server-{{ server.db.version|default('5.7') }}"
    state: present
    cache_valid_time: 86400

- name: Set MySQL root password
  command: /usr/bin/mysql -e "alter user 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY '{{ server.db.password }}';"
  ignore_errors: yes